[package]
name = "mocha_progress"
version = "0.0.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.26.1", default-features = false }
terminal_size = { version = "0.2.6", default-features = false }
