[package]
name = "mocha-std"
version = "0.0.0"
edition = "2021"

[dependencies]
rustix = { version = "0.38.21", default-features = false, features = ["mount", "pty", "std", "system", "thread"] }
rustix-uring = { version = "0.1.1", default-features = false, features = ["std"] }
