[package]
name = "mocha_ident"
version = "0.0.0"
edition = "2021"

[dependencies]
camino = { version = "1.1.4", default-features = false }
serde = { version = "1.0.163", default-features = false, features = ["std"] }
